TARGET = "sets/set10.py"
FIXES = [
 ("An Azure SQL Database requires multi-factor", "Microsoft account (organisational account) sign-in", "Microsoft account sign-in"),
 ("A query reads an Excel file from a local path", "The Source step must read the file's SharePoint URL (for example with Web.Contents or the SharePoint connectors) instead of File.Contents", "Read the SharePoint URL in the Source step"),
 ("Refresh fails with DataSource.NotFound", "It's a step-level error that stops the query from loading at all, whereas Remove errors only handles cell-level errors in rows", "It's a step-level error, not a cell-level one"),
 ("Refresh fails with DataSource.NotFound", "Remove errors must be the first step", "Remove errors must be placed directly after Source"),
 ("After merging Orders with Customers", "Customers has duplicate CustomerID values; check with Column distribution (unique vs distinct) or Keep duplicates on the key", "Duplicate CustomerID values in Customers"),
 ("After merging Orders with Customers", "The join kind was Inner", "The join kind was Inner instead of Left outer"),
 ("CSV files from a vendor change often", "Options → Data Load → Type detection: Never detect column types and headers for unstructured sources", "Options → Data Load → Type detection"),
 ("CSV files from a vendor change often", "Data source settings → Privacy", "Data source settings → Edit Permissions → Privacy level"),
 ("Power BI won't let you make a relationship active", "Keep one path active and leave the other relationship inactive, using USERELATIONSHIP where the second path is needed", "Make the other relationship inactive"),
 ("A table visual shows sales by day.", "Sales PrevMonth shows sales for 15 February; Sales Shifted shows all of February", "Sales PrevMonth shows sales for 15 February; Sales Shifted shows all of February's sales"),
 ("A measure must count new customers", "DISTINCTCOUNT ( Sales[CustomerKey] )", "COUNTROWS ( FILTER ( VALUES ( Sales[CustomerKey] ), CALCULATE ( MIN ( Sales[OrderDate] ), ALLSELECTED ( 'Date' ) ) >= MIN ( 'Date'[Date] ) ) )"),
 ("A measure must count new customers", "DISTINCTCOUNT counts all active customers.", "ALLSELECTED only looks back to the start of the selected range, so earlier buyers can count as new."),
 ("A measure fails with \"A table of multiple values", "Use SELECTEDVALUE ( Product[Category], \"Multiple\" ) instead of VALUES", "Use SELECTEDVALUE ( Product[Category], \"Multiple\" )"),
 ("A measure fails with \"A table of multiple values", "Wrap the measure in IFERROR", "Wrap the concatenation in IFERROR ( ..., \"Multiple\" )"),
 ("Before field parameters existed", "SWITCH ( SELECTEDVALUE ( MetricPicker[Metric] ), \"Revenue\", [Revenue], \"Profit\", [Profit], \"Units\", [Units], [Revenue] )", "SWITCH ( SELECTEDVALUE ( MetricPicker[Metric] ), \"Revenue\", [Revenue], \"Profit\", [Profit], \"Units\", [Units] )"),
 ("Before field parameters existed", "SUM ( MetricPicker[Metric] )", "SWITCH ( VALUES ( MetricPicker[Metric] ), \"Revenue\", [Revenue], \"Profit\", [Profit], \"Units\", [Units], [Revenue] )"),
 ("Before field parameters existed", "with a default when nothing or several are selected. The other expressions are invalid or ignore the selection.", "returning blank when nothing or several are selected. VALUES raises an error unless exactly one metric is selected, and the other expressions are invalid or ignore the selection."),
 ("In DAX query view, you've rewritten", "Use the CodeLens option above the definition to update the model with the changed measure", "Use the CodeLens update option above the definition"),
 ("In DAX query view, you've rewritten", "Copy it into a calculated column", "Copy the definition into a calculated column in the model"),
 ("A matrix with Customer and Product on the rows", "It forces every Customer × Product combination to be evaluated, even empty ones; turn it off unless empty rows are truly required", "It evaluates every Customer × Product pair; turn it off"),
 ("A matrix with Customer and Product on the rows", "It disables the model's compression; reload the model", "It disables the model's compression; reload the model in Desktop"),
 ("A paginated report must reuse the measures", "Use the Power BI semantic model as the paginated report's data source", "Use the semantic model as the data source"),
 ("A report has 20 bookmarks.", "Put the five bookmarks in a bookmark group and set the navigator to show that group", "Put the five in a bookmark group for the navigator"),
 ("A report has 20 bookmarks.", "Create five separate buttons", "Create five separate buttons, one per Sales bookmark"),
 ("Personalize visuals is on for the report", "Turn off personalisation for that visual (in its visual header options)", "Turn off personalisation for that visual only"),
 ("A screen-reader user needs to hear", "Show as a table (keyboard shortcut Alt+Shift+F11)", "Show as a table"),
 ("A screen-reader user needs to hear", "and it has a keyboard shortcut.", "and it has a keyboard shortcut, Alt+Shift+F11."),
 ("A bar chart shows sales by product, but users want it sorted", "Add Margin % to the visual's Tooltips well, then sort the visual by Margin %", "Add Margin % to Tooltips, then sort by it"),
 ("A bar chart shows sales by product, but users want it sorted", "Sort the Product table in Power Query", "Sort the Product table in Power Query by Margin %"),
 ("Anomaly detection flags a spike", "Add Category and Channel to the anomaly detection's Explain by fields", "Add Category and Channel to Explain by"),
 ("Anomaly detection flags a spike", "Increase the sensitivity", "Increase the sensitivity of the anomaly detection"),
 ("An executive dashboard must appear prominently", "Feature the dashboard on Home (feature content)", "Feature the dashboard on Home"),
 ("Ten semantic models import from ten different", "One standard gateway (or one cluster), with a connection for each database", "One standard gateway with ten connections"),
 ("Ten semantic models import from ten different", "Ten personal-mode gateways", "Ten personal-mode gateways, one per model"),
 ("The Deployment pipelines option is unavailable", "Assign the workspace to Premium, Premium Per User or Fabric capacity", "A Premium, PPU or Fabric capacity workspace"),
 ("The Deployment pipelines option is unavailable", "Turn on the XMLA endpoint in Desktop", "Turn on the XMLA read-write endpoint in Desktop"),
 ("Compliance must find out who viewed", "The Microsoft Purview audit log (or the Fabric activity log)", "The Microsoft Purview audit log"),
 ("Compliance must find out who viewed", "Performance Analyzer", "Performance Analyzer in Power BI Desktop"),
 ("A report in workspace B uses a semantic model", "Read permission on the semantic model in workspace A (for example by sharing the model or through an app)", "Read permission on the model in workspace A"),
 ("A report in workspace B uses a semantic model", "Build permission on the report", "Build permission on the report in workspace B"),
 ("A report in workspace B uses a semantic model", "Admin on workspace B", "The Admin role on workspace B for every Viewer"),
 ("An analyst applies the Confidential sensitivity label", "The label is applied to the report and semantic model in the service when they are new there, and protection travels with the file", "The label carries to the service with the report and model"),
 ("An analyst applies the Confidential sensitivity label", "The label is removed on publishing", "The label is removed when the file is published to the service"),
 ("Which design meets the control-tower requirement?", "A composite model: historical shipment data in Import, in-transit shipments in DirectQuery with automatic page refresh, and shared dimensions set to Dual", "A composite model: Import history, DirectQuery in-transit data, Dual dimensions"),
 ("Which design meets the control-tower requirement?", "DirectQuery for the whole model with no aggregation", "DirectQuery for the whole model, with automatic page refresh every five minutes"),
 ("How should you relate the Depot table to Shipments?", "An active relationship on OriginDepot and an inactive one on DestinationDepot, with destination measures using USERELATIONSHIP", "Active on OriginDepot, inactive on DestinationDepot"),
 ("How should you relate the Depot table to Shipments?", "Two active relationships", "Two active relationships, one on each of the depot columns"),
 ("How do you make the approved visual available", "A Fabric administrator adds it to Organizational visuals in the admin portal", "An admin adds it to Organizational visuals"),
 ("How do you make the approved visual available", "Embed it in the corporate theme", "Embed it in the corporate report theme file"),
 ("Which RLS design meets the depot-manager requirement?", "Static roles per depot pair", "A role filter on the Shipments table: VAR D = CALCULATETABLE ( VALUES ( DepotUsers[DepotID] ), DepotUsers[Email] = USERPRINCIPALNAME () ) RETURN Shipments[OriginDepot] IN D && Shipments[DestinationDepot] IN D"),
 ("Which RLS design meets the depot-manager requirement?", "Filtering Depot through the active relationship only covers the origin.", "Requiring both columns with && drops shipments to or from other depots. Filtering Depot through the active relationship only covers the origin."),
]
