TARGET = "sets/set01.py"
FIXES = [
 ("Your organisation has a certified semantic model", "Get data → Power BI semantic models, which creates a live connection", "Get data → Power BI semantic models"),
 ("The password of the SQL account", "File → Options and settings → Data source settings, select the source, then Edit Permissions", "Data source settings → select the source → Edit Permissions"),
 ("A report will be distributed as a Power BI template", "A Power Query parameter with a list of suggested values, used in a filter step", "A Power Query parameter used in a filter step"),
 ("A Product table has one row per ProductKey", "One-to-many from Product to Sales, single cross-filter direction", "One-to-many from Product to Sales, single direction"),
 ("A Product table has one row per ProductKey", "Many-to-many with both directions", "Many-to-many between Product and Sales, both directions"),
 ("You need the number of different customers", "COUNT ( Sales[CustomerKey] )", "CALCULATE ( COUNT ( Sales[CustomerKey] ), Sales[Amount] > 0 )"),
 ("Which measure returns sales for the same period", "CALCULATE ( [Total Sales], YEAR ( 'Date'[Date] ) - 1 )", "CALCULATE ( [Total Sales], 'Date'[Year] = YEAR ( TODAY () ) - 1 )"),
 ("Which measure returns sales for the same period", "YEAR(...) - 1 isn't a valid filter argument.", "Filtering on last calendar year ignores the period the user selected."),
 ("Performance Analyzer shows a table visual taking", "The measures and model used by the visual's query", "The measures and model behind the visual"),
 ("Performance Analyzer shows a table visual taking", "The visual's formatting options", "The visual's formatting options and conditional formatting"),
 ("Executives want to see monthly revenue", "Line chart with Month on the X-axis", "Line chart over the 24 months"),
 ("Executives want to see monthly revenue", "Pie chart", "Pie chart with one slice per month"),
 ("Executives want to see monthly revenue", "Table", "Table with one row per month"),
 ("The marketing team requires every new report", "Create a JSON report theme and apply it in each report", "Create and apply a JSON report theme"),
 ("The operations team needs a formatted list", "A paginated report built in Power BI Report Builder", "A paginated report (Power BI Report Builder)"),
 ("The operations team needs a formatted list", "A Power BI report page with a table visual", "A Power BI report page with a large table visual"),
 ("You want to add a Copilot narrative visual", "A workspace on a paid Fabric capacity F2 or higher, or Power BI Premium P1 or higher", "Paid Fabric capacity (F2 or higher) or Premium (P1 or higher)"),
 ("You want to add a Copilot narrative visual", "Any workspace, as long as you have a Pro licence", "Any workspace, as long as every author has a Pro licence"),
 ("You want to add a Copilot narrative visual", "A workspace on a Fabric trial capacity", "A workspace on a Fabric trial capacity with Copilot switched on"),
 ("When a user selects a value in a Region slicer", "Edit interactions: select the slicer and set the card's interaction to None", "Edit interactions: set the card to None"),
 ("Two buttons must switch the same page area", "Create two bookmarks with Display selected and Data cleared, each hiding one of the two visuals", "Two bookmarks, Display only (Data cleared), each hiding one visual"),
 ("Two buttons must switch the same page area", "Create two bookmarks with the Data option on", "Two bookmarks with Data and Display both on, each hiding one visual"),
 ("Two buttons must switch the same page area", "Create one bookmark per slicer value", "One bookmark per slicer value, each showing both visuals"),
 ("Field staff open a report on their phones", "Create a mobile layout for the page and place the key visuals on the phone canvas", "Create a mobile layout for the page"),
 ("Field staff open a report on their phones", "Create a dashboard", "Create a dashboard and pin the key visuals to it"),
 ("Report users can export the underlying rows", "Set the report's export data option to allow summarised data only", "Set export data to summarised data only"),
 ("Report users can export the underlying rows", "Apply a sensitivity label", "Apply a sensitivity label that blocks exports"),
 ("A bar chart of sales by product category is sorted", "Apply a Top N filter of 100", "Apply a Top N filter showing the top 100 categories by sales"),
 ("A manager wants to explore profit across region", "Waterfall chart", "Waterfall chart by region"),
 ("Three hundred sales staff need to view", "Publish an app from the workspace and give a security group access to it", "Publish an app and grant a security group access"),
 ("Three hundred sales staff need to view", "Add all 300 users to the workspace as Viewers", "Add all 300 users to the workspace with the Viewer role"),
 ("A semantic model imports data from a SQL Server database on the company network", "An on-premises data gateway with a connection to the SQL Server", "An on-premises data gateway"),
 ("How should you model sales and targets so both", "Create a shared Store dimension with one-to-many relationships to both the Sales and the Targets tables", "A shared Store dimension related one-to-many to both tables"),
 ("You create one role with a DAX filter that compares", "In the Power BI service, on the semantic model's Security page, by adding a security group of store managers", "In the service, on the semantic model's Security page, adding a group"),
 ("You create one role with a DAX filter that compares", "In the workspace access pane, as Contributors", "In the workspace access pane, adding the managers as Contributors"),
 ("You create one role with a DAX filter that compares", "In Power BI Desktop, in Manage roles", "In Power BI Desktop, under Modeling → Manage roles, before publishing"),
]
