TARGET = "sets/set04.py"
FIXES = [
 ("A report is live-connected to a shared semantic model", "Choose Make changes to this model, which turns the report into a composite model using DirectQuery to the semantic model", "Select Make changes to this model"),
 ("After applying changes, Power BI reports that 37 rows", "Select View errors, which creates a query showing the failing rows and their error messages", "Select View errors to open an errors query"),
 ("After applying changes, Power BI reports that 37 rows", "Turn on Column distribution", "Turn on Column quality and Column distribution"),
 ("After applying changes, Power BI reports that 37 rows", "Column distribution shows counts, not failing rows.", "Column quality and distribution show percentages and counts, not failing rows."),
 ("Report users want to drill from Year to Quarter", "A hierarchy on the Date table with Year, Quarter and Month levels", "A Year–Quarter–Month hierarchy on the Date table"),
 ("Report users want to drill from Year to Quarter", "A calculation group", "A calculation group with Year, Quarter and Month items"),
 ("Which is a good use case for a calculated table?", "A role-playing ShipDate table created as a copy of the existing Date table, without querying the source again", "A role-playing ShipDate table copied from the Date table"),
 ("Which is a good use case for a calculated table?", "Removing duplicate customers from the source", "Removing duplicate customers before they're loaded from the source"),
 ("In the Customer table, a calculated column CustSales", "Referencing a measure in a row context triggers context transition, turning the current customer row into a filter. SUM alone doesn't.", "Measure references trigger context transition; SUM doesn't"),
 ("In the Customer table, a calculated column CustSales", "Calculated columns can't use aggregation functions", "Calculated columns can't use aggregation functions such as SUM"),
 ("A card must show the combined sales of the top five", "RANKX ( ALL ( 'Product' ), [Total Sales] ) <= 5", "SUMX ( FILTER ( 'Product', RANKX ( 'Product', [Total Sales] ) <= 5 ), [Total Sales] )"),
 ("A card must show the combined sales of the top five", "The RANKX expression returns TRUE or FALSE.", "Ranking over 'Product' without ALL follows the visual's filters, so the top five change with them."),
 ("A fact table stores one row per sensor reading", "Group the data to one row per machine per day in Power Query before loading", "Group to one row per machine per day in Power Query"),
 ("A fact table stores one row per sensor reading", "Add a calculated column with the date", "Add a calculated column with the date and hide the timestamp"),
 ("Two large tables are related many-to-many", "Introduce a dimension with an integer surrogate key and use one-to-many relationships to both tables", "A dimension with integer keys, one-to-many to both tables"),
 ("Two large tables are related many-to-many", "Change the relationship direction to Both", "Change the many-to-many relationship's cross-filter direction to Both"),
 ("When users select a bar in a column chart", "In Edit interactions, change the target chart from Highlight to Filter", "Edit interactions: set the chart to Filter"),
 ("When users select a bar in a column chart", "Add a visual-level filter", "Add a visual-level filter to the target chart"),
 ("A line chart distinguishes Actual and Target", "Use different line styles or markers and label the series, and don't rely on colour alone", "Distinct line styles or markers, with labels"),
 ("A line chart distinguishes Actual and Target", "Change the background to black", "Change the background to black for more contrast"),
 ("A line chart distinguishes Actual and Target", "Make the lines thicker", "Make the lines thicker and the colours brighter"),
 ("Users don't know that they can right-click", "Set the button's action type to Drill through, with Customer Detail as the destination", "Set the action type to Drill through"),
 ("A data steward wants an email whenever a scheduled refresh", "In the semantic model's refresh settings, send refresh failure notifications to the steward as a contact", "Refresh failure notifications, with the steward as a contact"),
 ("A data steward wants an email whenever a scheduled refresh", "A data alert on a dashboard tile", "A data alert on a dashboard tile showing the last refresh date"),
 ("Content moves through Development, Test and Production", "Deployment rules for the semantic model in the Test and Production stages", "Deployment rules in the Test and Production stages"),
 ("Content moves through Development, Test and Production", "A separate .pbix file per stage", "A separate .pbix file per stage, each with its own source"),
 ("Where do you check, in the Power BI service", "On the semantic model's Security page, select the role's More options → Test as role", "Test as role, on the model's Security page"),
 ("Where do you check, in the Power BI service", "In the app's audience settings", "In the app's audience settings for that role"),
 ("Compliance requires that every report published", "A mandatory labelling policy in Microsoft Purview that applies to Power BI", "A mandatory labelling policy in Microsoft Purview"),
 ("Compliance requires that every report published", "A certification process", "A certification process for every published report"),
 ("How should you convert the balance text?", "Split the column by the space delimiter, change the amount to Decimal Number, then add a conditional column that multiplies by -1 when the indicator is DR", "Split on the space, type the amount, negate DR amounts"),
 ("How should you convert the balance text?", "Change the column type to Decimal Number directly", "Change the column type to Decimal Number using a locale"),
 ("The risk team keeps a hex colour per rating", "Create a measure that returns the hex colour, and apply background-colour conditional formatting by Field value using that measure", "Field value formatting with a measure that returns the hex colour"),
 ("The risk team keeps a hex colour per rating", "Create one rule per rating, typing each colour", "Create rules-based formatting with one rule per rating, typing each colour"),
 ("How do you make the scheduled refresh resilient", "Install a second gateway on another server and add it to the same gateway cluster", "Add a gateway on another server to the same cluster"),
 ("How do you make the scheduled refresh resilient", "Move refresh to 04:00", "Move the refresh to 04:00, when the gateway server is idle"),
]
