TARGET = "sets/set02.py"
FIXES = [
 ("Each month a new CSV file with the same columns", "Use the SharePoint folder connector, filter to the folder, and use Combine files", "Use the SharePoint folder connector and Combine files"),
 ("Ten semantic models in different workspaces", "A dataflow that produces the cleaned Customer table", "A dataflow for the cleaned Customer table"),
 ("Ten semantic models in different workspaces", "A calculated table in each model", "A calculated table in each of the ten models"),
 ("Ten semantic models in different workspaces", "A bookmark containing the steps", "A shared bookmark containing the 25 steps"),
 ("A numeric Discount column has a few cells", "Remove errors", "Remove errors from the Discount column"),
 ("A numeric Discount column has a few cells", "Remove blank rows", "Remove blank rows, then change the type"),
 ("A CSV from the German subsidiary", "Use Change Type → Using Locale, with type Decimal Number and locale German (Germany)", "Change Type → Using Locale, with locale German (Germany)"),
 ("A CSV from the German subsidiary", "Use Replace values to swap commas and dots", "Use Replace values to swap the commas and dots, then change type"),
 ("You need, for each customer, only their most recent", "Group by CustomerID with All rows, then extract the row with the latest OrderDate from each nested table", "Group by CustomerID (All rows), then take each table's latest row"),
 ("You need, for each customer, only their most recent", "Remove duplicates on CustomerID without sorting", "Remove duplicates on CustomerID without sorting the table first"),
 ("You need, for each customer, only their most recent", "Append the Orders query to itself", "Append the Orders query to itself, then remove duplicates"),
 ("You need, for each customer, only their most recent", "Pivot OrderDate", "Pivot the OrderDate column by CustomerID"),
 ("A Budget table holds amounts per product Category", "Create a Category dimension with one row per category, related one-to-many to both Product and Budget", "A Category dimension related one-to-many to both Product and Budget"),
 ("A Budget table holds amounts per product Category", "Relate Budget to Sales directly on Category", "Relate Budget directly to Sales on the Category column, many-to-many"),
 ("Sales managers want a slider", "A calculation group", "A calculation group with one item per discount rate"),
 ("Sales managers want a slider", "A bookmark", "A bookmark for each discount rate"),
 ("A Margin % measure shows 0.2381", "The measure's Format to Percentage with one decimal place", "The measure's format: Percentage, one decimal place"),
 ("A Margin % measure shows 0.2381", "Each visual's data label format", "Each visual's data label display units and decimals"),
 ("A Margin % measure shows 0.2381", "The DAX to multiply by 100", "The DAX, to multiply the result by 100 and round"),
 ("Sales has an Amount column.", "COUNTX ( Sales, 1000 )", "COUNTX ( Sales, Sales[Amount] > 1000 )"),
 ("Sales has an Amount column.", "SUM ( Sales[Amount] ) > 1000", "CALCULATE ( SUM ( Sales[Amount] ), Sales[Amount] > 1000 )"),
 ("Sales has an Amount column.", "The other expressions return TRUE or FALSE, or count every row.", "The others return TRUE or FALSE, count every row, or add up amounts instead of counting rows."),
 ("What is the main benefit of the VAR", "The variable is evaluated once and reused, which makes the measure easier to read and avoids calculating [Total Sales] twice", "Each variable is evaluated once, then reused in the RETURN"),
 ("What is the main benefit of the VAR", "Variables are stored in the model and reused by other measures", "Variables are stored in the model, so other measures can reuse their values"),
 ("What is the main benefit of the VAR", "VAR forces the measure to ignore slicers", "VAR fixes the filter context, so the measure ignores slicers"),
 ("A measure must return \"High\"", "LOOKUPVALUE ( [Margin %], \"High\" )", "SWITCH ( TRUE (), [Margin %] >= 0.2, \"Medium\", [Margin %] >= 0.4, \"High\", \"Low\" )"),
 ("A measure must return \"High\"", "LOOKUPVALUE retrieves column values.", "Testing 20% first returns Medium for every margin of 20% or more, so High is never reached."),
 ("A 200-million-row fact table", "Split it into a Date column and a Time column (or hour) in Power Query, and remove the original", "Split it into Date and hour columns, then remove the original"),
 ("A 200-million-row fact table", "Set the column's Summarize by to None", "Set the column's Summarize by to None and hide it from report view"),
 ("A 200-million-row fact table", "Mark the table as a date table", "Mark the fact table as a date table using this column"),
 ("A table shows revenue growth by product", "Conditional formatting → Icons, with rules on the growth value", "Conditional formatting → Icons on the growth column"),
 ("A table shows revenue growth by product", "Data bars on the growth column", "Conditional formatting → Data bars on the growth column"),
 ("A report will be shown on a wall display", "Canvas settings → Type: Custom, with a width and height matching 32:9", "Canvas settings → Custom size matching 32:9"),
 ("A report will be shown on a wall display", "The page view to Actual size", "The page view, set to Actual size instead of Fit to page"),
 ("You plan to use Copilot to create", "Add clear names, descriptions and synonyms to tables, columns and measures", "Add clear names, descriptions and synonyms"),
 ("You plan to use Copilot to create", "Switch every table to DirectQuery", "Switch every table to DirectQuery so Copilot sees live data"),
 ("You create a drillthrough page", "A Back button that returns users to the page they came from", "A Back button to the source page"),
 ("You create a drillthrough page", "A slicer on Category", "A Category slicer synced to the source page"),
 ("A Year slicer must keep the same selection", "In the Sync slicers pane, sync the slicer on pages 1–3 and leave page 4 unsynced", "Sync slicers: sync pages 1–3, leave page 4 unsynced"),
 ("A Year slicer must keep the same selection", "Use a report-level filter on Year", "Use a report-level filter on Year with a slicer on page 4"),
 ("A bar chart shows Revenue by Region", "Create a report-page tooltip", "Create a report-page tooltip that shows Margin %"),
 ("A column chart shows a sharp drop", "Right-click the April column and choose Analyze → Explain the decrease", "Analyze → Explain the decrease on the April column"),
 ("A column chart shows a sharp drop", "Add a trend line", "Add a trend line and an average line from the Analytics pane"),
 ("A column chart shows a sharp drop", "Add a forecast", "Add a forecast from the Analytics pane"),
 ("Users ask the Q&A visual about", "Add turnover as a synonym for the Revenue measure in Q&A setup or the model's synonyms", "Add turnover as a synonym for Revenue"),
 ("Users ask the Q&A visual about", "Add a smart narrative", "Add a smart narrative that mentions turnover"),
 ("A sales manager wants a snapshot", "A data alert", "A data alert on a dashboard tile"),
 ("A sales manager wants a snapshot", "A deployment pipeline", "A deployment pipeline with a weekly schedule"),
 ("A semantic model uses DirectQuery to an on-premises Oracle", "A standard on-premises data gateway, installed on a server and managed centrally", "A standard on-premises data gateway on a server"),
 ("A model must hide the Salary column", "Object-level security, authored with an external tool such as Tabular Editor", "Object-level security, authored in Tabular Editor"),
 ("A model must hide the Salary column", "Hiding the column in report view", "Hiding the column in report view, in Power BI Desktop"),
 ("After combining the files from the folder", "In the Transform Sample File query, use Remove Rows → Remove bottom rows (1 row)", "In Transform Sample File, remove the bottom row"),
 ("How do you meet the operations manager", "Pin a card showing today's late orders to a dashboard and set a data alert on the tile above 50", "Set a data alert on a dashboard tile of today's late orders"),
 ("How do you meet the operations manager", "Add conditional formatting to the card", "Set conditional formatting on the card to turn red above 50"),
 ("How do you meet the operations manager", "Create a subscription to the report page", "Create a daily subscription to the report page"),
]
