TARGET = "sets/set09.py"
FIXES = [
 ("A supplier sends a monthly price list as a PDF", "PDF, then select the detected table in the Navigator", "PDF, then pick the table in the Navigator"),
 ("A supplier sends a monthly price list as a PDF", "Text/CSV", "Text/CSV, with the delimiter set to a tab"),
 ("A supplier sends a monthly price list as a PDF", "Blank query", "Blank query with the table typed in"),
 ("An Excel workbook is stored in OneDrive for Business", "Use the file's OneDrive/SharePoint web URL (Web connector or the SharePoint connectors), not the local synced path", "Use the file's OneDrive/SharePoint web URL"),
 ("A report is live-connected to a published semantic model", "In a live connection you can add report-level measures, but not calculated columns or tables; to add them, use a composite model or change the source model", "Only report-level measures can be added, not columns"),
 ("Refresh fails with \"Expression.Error", "The source column was renamed or removed, and a step still refers to the old name", "A source column was renamed or removed"),
 ("Refresh fails with \"Expression.Error", "The gateway is offline", "The gateway is offline, so the source can't be read"),
 ("In an order-lines source, a null Quantity", "In Power Query, use Replace values to replace null with 0 in Quantity", "In Power Query, replace null with 0"),
 ("In an order-lines source, a null Quantity", "Delete the rows", "Delete the rows with a null Quantity"),
 ("A merge must match supplier names", "Fuzzy matching in the merge, with the list supplied as a transformation table", "Fuzzy merge with a transformation table"),
 ("A merge must match supplier names", "A Left anti join", "A Left anti join against the list of equivalents"),
 ("A merge must match supplier names", "Group by supplier name", "Group by supplier name and keep the first row"),
 ("You need an OrderSequence column", "Sort by CustomerID and OrderDate, group by CustomerID with All rows, add an index column starting at 1 inside each nested table, then expand", "Sort by OrderDate, group by CustomerID (All rows), and index each group"),
 ("You need an OrderSequence column", "Add one index column to the whole table", "Sort by CustomerID and OrderDate, then add one index column to the whole table"),
 ("You need an OrderSequence column", "A single index column numbers all rows continuously.", "A single index column numbers all rows continuously, even after sorting."),
 ("An Employee table has EmployeeID and ManagerID", "Create a Path column with PATH, then Level1–Level4 calculated columns with PATHITEM (and LOOKUPVALUE for names), and build a hierarchy from them", "Use PATH and PATHITEM to build Level1–Level4 columns"),
 ("An Employee table has EmployeeID and ManagerID", "Use a calculation group", "Use a calculation group with one item per level"),
 ("Users must slice customers by the year", "A calculated column: FirstPurchaseDate = CALCULATE ( MIN ( Sales[OrderDate] ) ), with a year column derived from it", "A calculated column using CALCULATE ( MIN ( Sales[OrderDate] ) )"),
 ("Users must slice customers by the year", "A measure: MIN ( Sales[OrderDate] )", "A measure: CALCULATE ( MIN ( Sales[OrderDate] ), ALLEXCEPT ( Sales, Sales[CustomerKey] ) )"),
 ("Users must slice customers by the year", "A visual calculation", "A visual calculation on a table of customers"),
 ("The fiscal year starts in April", "Add a FiscalMonthNumber column (April = 1 … March = 12) and set MonthName to sort by it", "Sort MonthName by a fiscal month number"),
 ("You need a cumulative (all-time running)", "SUM ( Sales[Amount] )", "CALCULATE ( [Total Sales], FILTER ( ALL ( 'Date'[Date] ), 'Date'[Date] <= MIN ( 'Date'[Date] ) ) )"),
 ("You need a cumulative (all-time running)", "A plain SUM is limited to the current period.", "Using MIN ends the total at the first date in the current context rather than the last."),
 ("A Rates table has one row per Date and Currency", "SUM ( Rates[Rate] )", "LOOKUPVALUE ( Rates[Rate], Rates[Date], MAX ( Sales[OrderDate] ), Rates[Currency], Sales[Currency] )"),
 ("A Rates table has one row per Date and Currency", "SUM and VALUES ignore the row's date and currency.", "MAX ( Sales[OrderDate] ) returns the latest order date in the table, not the row's own date. VALUES ignores the row's date and currency."),
 ("A 100-million-row Sales table", "Remove the copied columns and use the attributes from the dimension tables through the existing relationships", "Remove the copied columns"),
 ("A 100-million-row Sales table", "Set the relationships to Both", "Set the Product and Customer relationships to Both"),
 ("A 100-million-row Sales table", "Switch Product to DirectQuery", "Switch Product and Customer to DirectQuery storage"),
 ("A visual calculation must use Product[ListPrice]", "Add ListPrice to the visual (you can hide it from display), then reference it in the visual calculation", "Add ListPrice to the visual, hidden if needed"),
 ("A bar chart must show only the ten customers", "A visual-level Top N filter on Customer, by the Sales measure", "A visual-level Top N filter by Sales"),
 ("A model has 80 measures with no descriptions", "Copilot's option to create measure descriptions from each measure's DAX, reviewing each before saving", "Copilot to draft each measure's description"),
 ("A model has 80 measures with no descriptions", "DAX query view's EVALUATE", "DAX query view, with EVALUATE over INFO.MEASURES ()"),
 ("You changed which visuals a bookmark hides", "Select the bookmark, apply the new state on the page, then use Update on the bookmark", "Use Update on the bookmark"),
 ("You changed which visuals a bookmark hides", "Rename the bookmark", "Rename the bookmark to refresh its state"),
 ("Users type \"big orders\" in Q&A", "Use Teach Q&A to define \"big orders\" as orders where Amount is greater than 10,000", "Use Teach Q&A to define \"big orders\""),
 ("Users type \"big orders\" in Q&A", "Add a smart narrative", "Add a smart narrative that explains the term"),
 ("On a scatter chart of stores", "Create a measure that flags outliers (a z-score above 3) and apply marker colour conditional formatting by rule (or field value) using it", "Colour markers by rule on a z-score measure"),
 ("On a scatter chart of stores", "Use clustering only", "Use clustering to group the stores automatically"),
 ("On a scatter chart of stores", "Increase the marker size", "Increase the marker size for stores with high margin"),
 ("A Pro workspace model's scheduled refresh stopped", "The service pauses scheduled refresh after two months of inactivity", "Refresh pauses after two months of inactivity"),
 ("A Pro workspace model's scheduled refresh stopped", "Pro licences expire every month", "Pro licences must be renewed by the admin every month"),
 ("Viewers of a workspace must not see a draft", "Distribute to consumers through an app that excludes the draft, and keep consumers out of the workspace itself", "Publish an app that excludes the draft"),
 ("Users find a certified semantic model", "Certification shows trust but doesn't grant access; users still need permission on the model (they can request it)", "Certification doesn't grant access to the model"),
 ("How should you turn Payload into columns?", "Select Payload, choose Transform → Parse → JSON, then expand the resulting record into snowCm and tempC and set numeric types", "Transform → Parse → JSON, then expand the record"),
 ("How should you turn Payload into columns?", "Split Payload by the comma delimiter", "Split Payload by the comma delimiter, then by the colon"),
 ("How do you build the map hover experience?", "Create a report page tooltip with the 30-day snow chart, and set the map's tooltip to that page", "A report page tooltip set on the map"),
 ("How do you build the map hover experience?", "Create a drillthrough page", "A drillthrough page with the 30-day snow chart"),
 ("How do you build the map hover experience?", "Add snow depth to the map's size", "Add snow depth to the map's bubble size"),
 ("How do you build the map hover experience?", "Use a bookmark", "A bookmark"),
 ("How do you meet the refresh requirement?", "Configure scheduled refresh in 30-minute slots from 08:00 to 17:00. The capacity allows up to 48 refreshes a day, and the on-premises source needs a standard gateway.", "Half-hourly scheduled refresh through a standard gateway"),
 ("How do you meet the refresh requirement?", "It isn't possible; the maximum is 8 refreshes a day", "It isn't possible; the maximum is 8 refreshes a day on any capacity"),
]
