TARGET = "sets/set07.py"
FIXES = [
 ("A Direct Lake semantic model built on a lakehouse", "Queries against a SQL view fall back to DirectQuery, because Direct Lake reads Delta tables only", "Views fall back to DirectQuery; Direct Lake reads Delta tables only"),
 ("A Direct Lake semantic model built on a lakehouse", "Direct Lake caches views for 24 hours", "Direct Lake re-imports views on every query instead of caching them"),
 ("A DirectQuery report queries a large SQL function", "A dynamic M query parameter bound to the slicer's column", "A dynamic M query parameter bound to the slicer"),
 ("A DirectQuery report queries a large SQL function", "A what-if parameter", "A what-if parameter whose value the M query reads"),
 ("On Premium capacity, a sales table holds five years", "Incremental refresh with the option to get the latest data in real time with DirectQuery (a hybrid table)", "Incremental refresh with real-time DirectQuery data (a hybrid table)"),
 ("On Premium capacity, a sales table holds five years", "Import with 48 scheduled refreshes", "Import with 48 scheduled refreshes a day, one every 30 minutes"),
 ("On Premium capacity, a sales table holds five years", "A separate report for today", "A separate DirectQuery report for today's orders only"),
 ("On Premium capacity, a sales table holds five years", "DirectQuery for the whole table", "DirectQuery for the whole table, including the five years of history"),
 ("With profiling switched to the entire data set", "Every value occurs exactly once, so the column can act as the key of a dimension", "Every value occurs once, so it can be a dimension key"),
 ("With profiling switched to the entire data set", "The column has many duplicates", "The column has many duplicates, so it can't be used as a key"),
 ("The data team must review rows that fail type conversion", "Create a reference query that uses Keep errors for review (not loaded), and use Remove errors in the main query", "Keep errors in an unloaded reference query; Remove errors in the main query"),
 ("The data team must review rows that fail type conversion", "Load both valid and invalid rows into the model", "Load both valid and invalid rows into the model, and hide the invalid ones with a report filter"),
 ("When you configure incremental refresh, Power BI warns", "Remove the index step, or move the date filter before it, so the filter folds to the source", "Move the date filter before the index step, or remove the index"),
 ("When you configure incremental refresh, Power BI warns", "Ignore the warning; folding isn't relevant", "Ignore the warning; folding only affects DirectQuery, not incremental refresh"),
 ("A JSON field named tags holds a list", "Use Extract Values on the list column with a comma delimiter", "Extract Values on the list, with a comma delimiter"),
 ("A JSON field named tags holds a list", "Expand the list to new rows", "Expand the list to new rows, then remove duplicates"),
 ("In a composite model, an imported Budget table", "RELATED can't be used across a limited relationship, and no blank row is added for unmatched values", "RELATED can't cross it, and no blank row is added for unmatched values"),
 ("RLS is defined on a Users table", "Set cross-filter direction to Both and turn on Apply security filter in both directions", "Set it to Both and turn on Apply security filter in both directions"),
 ("RLS is defined on a Users table", "Make the relationship inactive", "Make the relationship inactive and activate it with USERELATIONSHIP in the role"),
 ("An AgeBand column", "As far upstream as possible: in the source or in Power Query, rather than as a DAX calculated column", "In the source or Power Query"),
 ("An AgeBand column", "In each report as a group", "In each report, as a group on the Age column"),
 ("An AgeBand column", "As a measure", "As a measure that returns the band for each customer"),
 ("A calculation group has items Current, PY and YoY %", "A dynamic format string expression on the YoY % calculation item", "A dynamic format string on the YoY % calculation item"),
 ("A calculation group has items Current, PY and YoY %", "The Format property of the calculation group column", "The Format property of the calculation group column in the model"),
 ("A DirectQuery fact table has 5 billion rows", "Configure Manage aggregations on the summary table, mapping its columns to the detail table", "Manage aggregations on the summary table, mapped to the detail table"),
 ("A DirectQuery fact table has 5 billion rows", "Create a relationship between the summary and the detail table", "Create a relationship between the summary and the detail table on their keys"),
 ("A Power BI report page must show an operational paginated report", "The Paginated report visual, mapping report fields to the paginated report's parameters", "The Paginated report visual, with fields mapped to its parameters"),
 ("A Power BI report page must show an operational paginated report", "A web URL to Report Builder", "A web URL to Report Builder with the parameters in the query string"),
 ("Across 40 reports, every new card visual", "Add visualStyles settings for the card visual to the corporate JSON theme", "Add card visualStyles to the corporate JSON theme"),
 ("Across 40 reports, every new card visual", "Copy one formatted card into every report", "Copy one formatted card into every report and use it as a template"),
 ("In an Import-mode report, the Page refresh option is missing", "Automatic page refresh is only available for pages using DirectQuery (or other supported live) sources", "It's only available for DirectQuery and similar sources"),
 ("In an Import-mode report, the Page refresh option is missing", "Page refresh requires a mobile layout", "Page refresh needs a mobile layout before it appears in settings"),
 ("Each chart's alt text must describe its current values", "Use conditional formatting (fx) on the Alt text property with a measure that builds the description", "Set the Alt text with fx to a measure that builds the description"),
 ("Each chart's alt text must describe its current values", "Type a fixed alt text for each chart", "Type a fixed alt text for each chart that includes this month's value"),
 ("Two different slicers, one on page 1", "In Sync slicers advanced options, give both slicers the same group name", "Give both slicers the same group name in Sync slicers"),
 ("Two different slicers, one on page 1", "Use a report-level filter", "Use a report-level filter on Date[Year] instead of slicers"),
 ("Across a whole report, selecting a data point should cross-filter", "The report setting that changes the default visual interaction from cross-highlighting to cross-filtering", "The report's default visual interaction setting"),
 ("Across a whole report, selecting a data point should cross-filter", "Each visual's format pane", "Each visual's format pane, under the Interactions card"),
 ("Across a whole report, selecting a data point should cross-filter", "Persistent filters", "The persistent filters setting for the report"),
 ("The team wants to deploy metadata changes", "XMLA endpoint set to Read Write on the capacity", "XMLA endpoint set to Read Write"),
 ("The team wants to deploy metadata changes", "Persistent filters", "Persistent filters on the semantic model"),
 ("In a deployment pipeline, the compare view", "Select only the changed report and deploy it (selective deployment)", "Select only the changed report and deploy it"),
 ("In a deployment pipeline, the compare view", "Publish from Desktop directly to Test", "Publish the report from Desktop directly to the Test workspace"),
 ("On Premium capacity, a Sales dashboard must show data", "Scheduled refresh is set in 30-minute slots up to 48 times a day; use DirectQuery or a hybrid table for fresher data", "Refresh runs in 30-minute slots; use DirectQuery or a hybrid table"),
 ("On Premium capacity, a Sales dashboard must show data", "Premium allows only 8 refreshes per day", "Premium allows only 8 refreshes per day; use a Pro workspace instead"),
 ("A DirectQuery model uses an on-premises SQL Server", "Single sign-on (SSO) for DirectQuery on the gateway data source connection", "SSO for DirectQuery on the gateway data source"),
 ("A DirectQuery model uses an on-premises SQL Server", "RLS roles with USERNAME()", "RLS roles with USERNAME() that copy the SQL filters"),
 ("The organisation must stop all content from being shared", "In the Fabric admin portal tenant settings for external sharing and guest access", "In the Fabric admin portal tenant settings"),
 ("The organisation must stop all content from being shared", "In the workspace's licence mode", "In each workspace's licence mode and access settings"),
 ("One workspace app must show the Sales audience", "App audiences, with each report included only in the right audiences and each audience granted to its security group", "App audiences, each with the right reports and security group"),
 ("One workspace app must show the Sales audience", "Two workspaces with copies of the shared reports", "Two separate workspaces and apps, each with copies of the shared reports"),
 ("How should the live traffic page get its data?", "DirectQuery to the KQL database, with automatic page refresh at a short interval", "DirectQuery to the KQL database with automatic page refresh"),
 ("How should the live traffic page get its data?", "Import from the Eventhouse with scheduled refresh", "Import from the Eventhouse with scheduled refresh every minute"),
 ("Which change will most reduce the overview page's load time?", "Replace the 14 cards with a few multi-value visuals, such as a card visual showing several measures, so fewer queries queue", "Replace the 14 cards with a few multi-value visuals"),
 ("Which change will most reduce the overview page's load time?", "Rewrite each measure with variables", "Rewrite each card's measure with variables to cut its query time"),
 ("You add dynamic RLS for regions", "Make the analysts Viewers in the workspace and give them Build permission on the model, so RLS applies while they can still create reports", "Make the analysts Viewers with Build permission on the model"),
 ("You add dynamic RLS for regions", "Add the analysts to a second role", "Add the analysts to a second role with the same region filter"),
]
