TARGET = "sets/set08.py"
FIXES = [
 ("One Excel workbook holds 12 monthly sheets", 'Connect to the workbook, filter the navigation table to Kind = "Sheet", then expand the Data column', 'Filter the navigation table to Kind = "Sheet", then expand Data'),
 ("One Excel workbook holds 12 monthly sheets", "Connect to each sheet separately and append them", "Connect to each sheet separately and append the twelve queries together"),
 ("One Excel workbook holds 12 monthly sheets", "Use the Folder connector on the workbook", "Use the Folder connector pointed at the workbook's file path"),
 ("The SharePoint folder connector asks for a URL", "The full folder URL including /Exports", "The full folder URL: .../sites/Finance/Shared Documents/Exports"),
 ("Twenty CSV sources need the same 15 cleaning steps", "A custom function (Create Function from a query), then Invoke Custom Function on each source", "A custom function, invoked on each source"),
 ("Twenty CSV sources need the same 15 cleaning steps", "Twenty duplicated queries", "Twenty duplicated queries, one per CSV source"),
 ("Twenty CSV sources need the same 15 cleaning steps", "A calculation group", "A calculation group with one item per source"),
 ("A Tickets table has a Status column", "Pivot the Status column, with TicketID as the values and the aggregation set to Count", "Pivot the Status column, counting TicketID"),
 ("A Tickets table has a Status column", "Unpivot the Status column", "Unpivot the Status column into attribute-value pairs"),
 ("A fact table has eight low-cardinality", "A junk dimension holding the distinct flag combinations, related to the fact by one key", "A junk dimension of the distinct flag combinations"),
 ("A fact table has eight low-cardinality", "A separate dimension table per flag", "A separate dimension table for each of the eight flags"),
 ("Sales has an OrderNumber column", "No. Keep OrderNumber in the fact table as a degenerate dimension.", "No. Keep it in the fact table as a degenerate dimension."),
 ("Sales has an OrderNumber column", "Yes. Every column must move to a dimension.", "Yes. Every descriptive column must move to a dimension table."),
 ("Sales has an OrderNumber column", "Yes, with a many-to-many relationship", "Yes, related to Sales with a many-to-many relationship"),
 ("A Store table has Latitude and Longitude", "Data category Latitude and Longitude on the respective columns, and use them in the map's Latitude and Longitude wells", "Data category Latitude and Longitude on the respective columns"),
 ("A Store table has Latitude and Longitude", "Data category City on both columns", "Data category City on both columns, placed in the map's Location well"),
 ("A calculation group's YTD item", "SELECTEDMEASURE () * 0", "IF ( SELECTEDMEASURENAME () = \"Margin %\", CALCULATE ( SELECTEDMEASURE (), DATESYTD ( 'Date'[Date] ) ), SELECTEDMEASURE () )"),
 ("A calculation group's YTD item", "The other expressions don't implement YTD.", "Swapping the IF branches applies YTD only to Margin %, and the ISBLANK test doesn't implement YTD."),
 ("Which measure returns the quantity-weighted", "SUM ( Sales[UnitPrice] ) / COUNTROWS ( Sales )", "DIVIDE ( SUMX ( Sales, Sales[Quantity] * Sales[UnitPrice] ), COUNTROWS ( Sales ) )"),
 ("Which measure returns the quantity-weighted", "The other expressions give each order line equal weight, whatever its quantity.", "AVERAGE and AVERAGEX give each order line's price equal weight, whatever its quantity, and dividing revenue by the row count gives revenue per line, not price per unit."),
 ("A disconnected Band table", "CALCULATE ( COUNTROWS ( Customer ), Band[Min] > 0 )", "COUNTROWS ( FILTER ( Customer, SUM ( Sales[Amount] ) >= MIN ( Band[Min] ) && SUM ( Sales[Amount] ) < MAX ( Band[Max] ) ) )"),
 ("A disconnected Band table", "Counting the Band table or filtering it doesn't evaluate customers.", "SUM inside FILTER has no context transition, so it tests the same total for every customer rather than each customer's own sales. Counting the Band table or its bands doesn't evaluate customers."),
 ("A model loads ten years of transactions", "Filter the query in Power Query to keep only the last two years", "Filter the query in Power Query to the last two years"),
 ("A model loads ten years of transactions", "Add a page filter for the last two years", "Add a report-level filter that keeps only the last two years"),
 ("A model loads ten years of transactions", "Create a measure that ignores old dates", "Create measures that ignore dates older than two years"),
 ("A table visual lists every transaction", "Add filters (such as a recent-date filter or required selection) so the visual returns far fewer rows", "Add filters so the visual returns far fewer rows"),
 ("A table visual lists every transaction", "Turn off totals only", "Turn off totals and keep the visual otherwise unchanged"),
 ("A narrative visual with Copilot", "In the narrative visual's settings, choose to summarise selected visuals and pick the three", "Scope the visual to summarise selected visuals"),
 ("A narrative visual with Copilot", "Use a text box instead", "Replace it with a text box that describes the KPIs"),
 ("A narrative visual with Copilot", "Delete the other visuals", "Delete the other visuals from the page"),
 ("A chart must show monthly revenue as columns", "Line and clustered column chart, with margin % on the secondary axis", "Line and clustered column chart with a secondary axis"),
 ("A chart must show monthly revenue as columns", "Clustered bar chart only", "Clustered column chart with both measures on one axis"),
 ("A slicer must let users pick a year", "Add Year and Month (or a date hierarchy) to the slicer's field well to make a hierarchy slicer", "Make a hierarchy slicer with Year and Month"),
 ("A slicer must let users pick a year", "Use two unsynced slicers", "Use two slicers, one for Year and one for Month"),
 ("A slicer must let users pick a year", "Use a between date slicer", "Use a between date slicer on the Date column"),
 ("A report-page tooltip about product categories", "Add Product[Category] to the tooltip page's Tooltip fields well", "Add Product[Category] to its Tooltip fields well"),
 ("A report-page tooltip about product categories", "Set each visual's tooltip to Default", "Set the Tooltip option to Default on each visual that uses Category"),
 ("When users drill down from Year to Quarter", "Format ribbon → Interactions → turn on Drilling filters other visuals", "Turn on Drilling filters other visuals"),
 ("When users drill down from Year to Quarter", "Edit interactions to None", "Set Edit interactions to None for the chart"),
 ("A report is always saved by authors", "Make Overview the active page when you save and publish the report", "Save and publish with Overview as the active page"),
 ("A report is always saved by authors", "Create a bookmark navigator", "Add a bookmark navigator with Overview as its first bookmark"),
 ("You can't find the Find anomalies option", "Turn on data labels", "Switch the X-axis to categorical in the column chart"),
 ("You can't find the Find anomalies option", "Column charts, legends and labels don't enable it.", "Column charts, legends and a categorical axis don't enable it."),
 ("The service-level target is that 95%", "A constant line at 0.95 from the Analytics pane", "A constant line at 0.95"),
 ("The service-level target is that 95%", "An average line", "An average line from the Analytics pane"),
 ("The service-level target is that 95%", "A trend line", "A trend line on the weekly on-time rate"),
 ("Analysts outside the Finance workspace", "Make the endorsed model discoverable, so users without access can find it and request access", "Make the endorsed model discoverable"),
 ("Analysts outside the Finance workspace", "Remove its endorsement", "Remove its endorsement so it shows in search"),
 ("Users requesting access to a workspace's content", "The workspace's Contact list in workspace settings", "The workspace contact list"),
 ("Users requesting access to a workspace's content", "A deployment rule", "A deployment rule in the pipeline"),
 ("A newly published app must appear automatically", "When publishing the app, turn on the option to install it automatically for the audience (allowed by a tenant setting)", "Turn on automatic install for the app audience"),
 ("A newly published app must appear automatically", "Add everyone as workspace Viewers", "Add the Sales group to the workspace as Viewers"),
 ("A newly published app must appear automatically", "Send everyone the workspace URL", "Share the workspace URL with the Sales group by email"),
 ("Users belong to a Region role", "Create one role whose filters cover both Region and Category, and assign users only to it", "Create one role filtering both Region and Category"),
 ("You're publishing a workspace app", "In the app's permissions, allow app users to build content with the underlying semantic models (grant Build)", "Grant app users Build permission on the semantic models"),
 ("You're publishing a workspace app", "Turn on persistent filters", "Turn on persistent filters so users can save their views"),
 ("Policy says users may lower a report's sensitivity label", "A label policy setting that requires justification to remove a label or lower its classification", "A label policy that requires justification"),
 ("Policy says users may lower a report's sensitivity label", "Certification of the report", "Certification of the report by a Fabric admin"),
 ("Policy says users may lower a report's sensitivity label", "An app audience", "An app audience restricted to label owners"),
 ("Which measure counts customers active at the start", "DISTINCTCOUNT ( Customer[StartDate] )", "VAR S = MAX ( 'Date'[Date] ) RETURN COUNTROWS ( FILTER ( Customer, Customer[StartDate] < S && ( ISBLANK ( Customer[ChurnDate] ) || Customer[ChurnDate] >= S ) ) )"),
 ("Which measure counts customers active at the start", "COUNTROWS(Customer) counts everyone.", "Using MAX tests the end of the period instead. COUNTROWS(Customer) counts everyone."),
 ("How should you show churn by tenure bucket?", "Create bins on TenureMonths with a bin size of 6, and plot churn rate by the bins", "Create bins of size 6 on TenureMonths"),
 ("How should you show churn by tenure bucket?", "Add a forecast on tenure", "Add a forecast on tenure in six-month steps"),
 ("How do you meet the Teams requirement?", "Add the report as a tab in the leadership Teams channel (or share the app in Teams)", "Add the report as a tab in the leadership Teams channel"),
 ("How do you meet the Teams requirement?", "Use Publish to web and post the link", "Use Publish to web and post the link in the channel"),
 ("How do you meet the Teams requirement?", "Export the report to PDF weekly", "Export the report to PDF weekly and post it in the channel"),
]
