TARGET = "sets/set06.py"
FIXES = [
 ("A PaymentType column contains Card", "Apply Format → Capitalize Each Word (or Uppercase) to standardise the text", "Apply Format → Capitalize Each Word or Uppercase"),
 ("A PaymentType column contains Card", "Filter out the lowercase values", "Filter out the lowercase and mixed-case values"),
 ("A PaymentType column contains Card", "Remove duplicates on PaymentType", "Remove duplicates on PaymentType, keeping the first spelling"),
 ("Column profile shows negative values in Quantity", "Add a conditional column TransactionType = \"Return\" when Quantity < 0, otherwise \"Sale\"", "Add a conditional column flagging rows with Quantity < 0 as \"Return\""),
 ("Column profile shows negative values in Quantity", "Replace negative values with 0", "Replace negative values with 0 and keep the rows"),
 ("Column profile shows negative values in Quantity", "Remove the negative rows", "Move the negative rows into a separate Returns query that isn't loaded"),
 ("The automatic Changed Type step detected", "Change the column's type to Text in the Changed Type step", "Change the column's type to Text"),
 ("The automatic Changed Type step detected", "Replace errors with 0", "Replace errors with 0 after the Changed Type step"),
 ("You need one row per Region showing total sales", "Group by Region with Advanced, adding Sum of Sales and Max of OrderDate", "Group by Region (Advanced): Sum of Sales, Max of OrderDate"),
 ("You need one row per Region showing total sales", "Group by Region with Basic, Count rows", "Group by Region (Basic) with Sum of Sales, then sort by OrderDate"),
 ("In Power Query, Sales must look up a price", "Merge queries selecting Region and ProductCode in both tables, in the same order", "Merge on Region and ProductCode, selected in the same order"),
 ("In Power Query, Sales must look up a price", "Create two separate merges and combine the results", "Create two separate merges, one per column, and combine the results"),
 ("Power BI created a many-to-many relationship between Customer and Sales", "Remove duplicate rows from the Customer query, then set the relationship to one-to-many", "Remove duplicate customers, then make it one-to-many"),
 ("A Size column has values S, M, L and XL", "Add a SizeOrder column (1–4) and set Size to sort by SizeOrder", "Add a SizeOrder column and sort Size by it"),
 ("A Size column has values S, M, L and XL", "Rename the values 1-S, 2-M and so on", "Rename the values 1-S, 2-M, 3-L and 4-XL"),
 ("A Size column has values S, M, L and XL", "Sort each visual by a measure", "Sort each visual by a measure that returns 1–4"),
 ("You need a model measure, usable in any visual, that returns the average of the last three months", "AVERAGE ( Sales[Amount] )", "CALCULATE ( AVERAGEX ( VALUES ( Sales[OrderDateKey] ), [Total Sales] ), DATESINPERIOD ( 'Date'[Date], MAX ( 'Date'[Date] ), -3, MONTH ) )"),
 ("You need a model measure, usable in any visual, that returns the average of the last three months", "AVERAGE(Sales[Amount]) is an average line value.", "Iterating the order dates inside the window also averages per day rather than per month."),
 ("An analyst who doesn't write DAX needs a running total", "Use a quick measure, choosing Running total, with Total Sales and Date", "Use a quick measure (Running total)"),
 ("An analyst who doesn't write DAX needs a running total", "Create a calculated column with SUM", "Create a calculated column with SUM over Sales"),
 ("A sensor table stores temperatures", "Round the values to two decimals in Power Query before loading", "Round to two decimals in Power Query"),
 ("A sensor table stores temperatures", "Add a measure that rounds the value", "Add a measure that rounds the value to two decimals"),
 ("When you open the Copilot pane in Power BI Desktop", "Copilot runs against a workspace assigned to a capacity that supports it, and that's how its use is enabled and charged", "Copilot needs a workspace on a capacity that supports it"),
 ("When you open the Copilot pane in Power BI Desktop", "The semantic model will be moved to that workspace", "The semantic model will be moved to that workspace to run Copilot"),
 ("A matrix has Category, Subcategory and Product on rows", "Use Expand all down one level in the hierarchy (the double-arrow fork icon)", "Use Expand all down one level in the hierarchy"),
 ("A matrix has Category, Subcategory and Product on rows", "Use drillthrough", "Use drillthrough to a page with a flat table"),
 ("A matrix has Category, Subcategory and Product on rows", "Use a tooltip page", "Use a report-page tooltip that lists every level"),
 ("In a table visual, users want rows sorted by Region", "Sort by Region, then Shift-click the Sales column header to add it as a secondary sort", "Sort by Region, then Shift-click the Sales header"),
 ("In a table visual, users want rows sorted by Region", "Create a calculated column combining both", "Create a calculated column combining Region and Sales, and sort by it"),
 ("The Key influencers visual must explain what drives a numeric outcome", "Yes: it shows factors associated with the price increasing, such as \"when bedrooms goes up by 1, price increases by 25k\"", "Yes: it shows how each factor moves the average price"),
 ("A column chart shows product mix by region", "Right-click North → Analyze → Find where this distribution is different", "Analyze → Find where this distribution is different"),
 ("A column chart shows product mix by region", "Explain the increase", "Right-click North → Analyze → Explain the increase"),
 ("A column chart shows product mix by region", "Add a forecast", "Add a forecast for each region from the Analytics pane"),
 ("A report author keeps the .pbix file on a SharePoint Online site", "Upload the file from OneDrive or SharePoint, which keeps it synchronised", "Upload it from SharePoint in the service"),
 ("A report author keeps the .pbix file on a SharePoint Online site", "Publish from Desktop each time", "Publish from Desktop each time the file changes"),
 ("A report author keeps the .pbix file on a SharePoint Online site", "Use Publish to web", "Use Publish to web with the SharePoint file's link"),
 ("After publishing a model that imports from an on-premises SQL Server", "Add a connection for the SQL Server on the gateway (if none exists) and map the model's data source to it in Gateway and cloud connections", "Map the source to a gateway connection for the server"),
 ("After publishing a model that imports from an on-premises SQL Server", "Install a personal gateway on your laptop", "Install a personal gateway on your laptop and sign in to it"),
 ("After publishing a model that imports from an on-premises SQL Server", "Switch the model to DirectQuery", "Switch the model to DirectQuery so no gateway is needed"),
 ("After publishing a model that imports from an on-premises SQL Server", "Republish the model", "Republish the model from Desktop with credentials saved"),
 ("A manager sets a data alert on a dashboard tile", "Data alerts are personal: they notify only the user who created them (Power Automate can extend the notification)", "Data alerts are personal: only their creator is notified"),
 ("A manager sets a data alert on a dashboard tile", "The team needs Admin on the workspace", "The team needs the Admin role on the dashboard's workspace"),
 ("An external auditing firm must view three reports", "Invite the auditors as Microsoft Entra B2B guest users and share the reports (or an app) with them", "Invite them as Entra B2B guests and share the reports"),
 ("An external auditing firm must view three reports", "Email PDF exports", "Email them PDF exports of the three reports each month"),
 ("A report with the Highly Confidential label", "The file carries the label and its protection, so only authorised users can open it", "It keeps the label and its protection"),
 ("A report with the Highly Confidential label", "The export is always blocked", "The export is always blocked for encrypted labels"),
 ("How should you model dealers and territories?", "Add a DealerTerritory bridge table, related one-to-many from Territory and from Dealer, with the bridge–Dealer relationship set to Both so Territory can filter Dealer and Sales", "Add a DealerTerritory bridge, with bridge–Dealer filtering set to Both"),
 ("How do you deliver the Monday PDF to each dealer contact?", "Create a subscription to the report with the full report attached as PDF, scheduled weekly", "A weekly subscription with the report attached as PDF"),
 ("How do you deliver the Monday PDF to each dealer contact?", "Set a data alert", "Set a data alert that emails the PDF to every dealer contact on Mondays"),
]
