TARGET = "sets/set03.py"
FIXES = [
 ("A Country column contains about 40 spellings", "Keep a mapping table of variant and correct names, merge it with the query, and use the correct name", "Merge a mapping table of variant and correct names"),
 ("A Country column contains about 40 spellings", "Add 40 Replace values steps", "Add a Replace values step for each of the 40 spellings"),
 ("A Country column contains about 40 spellings", "Use Capitalize Each Word", "Use Capitalize Each Word, then Trim and Clean"),
 ("The source view keeps gaining new columns", "Choose columns (Remove other columns) to keep the six you need", "Choose columns (Remove other columns)"),
 ("Product filters Sales, and Customer filters Sales", "Use CALCULATE ( COUNTROWS ( Customer ), CROSSFILTER ( Sales[CustomerKey], Customer[CustomerKey], BOTH ) )", "Use CROSSFILTER with BOTH on that relationship inside the measure's CALCULATE"),
 ("Product filters Sales, and Customer filters Sales", "Set the Customer–Sales relationship to Both", "Set the Customer–Sales relationship's cross-filter direction to Both in the model"),
 ("Customer and CustomerDetails share CustomerID", "Merge CustomerDetails into Customer in Power Query and load a single table", "Merge CustomerDetails into Customer in Power Query"),
 ("A Targets table has a MonthStart column", "RELATED ( Targets[Amount] )", "CALCULATE ( SUM ( Targets[Amount] ), USERELATIONSHIP ( 'Date'[MonthStart], Targets[MonthStart] ) )"),
 ("A Targets table has a MonthStart column", "RELATED needs a physical relationship and a row context.", "USERELATIONSHIP only activates an existing inactive relationship, and there isn't one."),
 ("Performance Analyzer shows that most visuals", "Visuals are waiting for other visuals to finish, so reduce the number of visuals on the page", "Visuals wait on other visuals, so use fewer visuals"),
 ("Performance Analyzer shows that most visuals", "The DAX measures are slow, so rewrite them", "The DAX measures are slow, so rewrite them with variables"),
 ("Performance Analyzer shows that most visuals", "The theme is too complex, so remove it", "The custom theme is too complex, so revert to the default"),
 ("A DirectQuery report sends a query to the source", "Query reduction: add an Apply button to slicers (and filters)", "Query reduction: add Apply buttons to slicers"),
 ("A DirectQuery report sends a query to the source", "Switch the slicers to dropdown style", "Switch the slicers to dropdown style so fewer queries run"),
 ("An analyst wants to see whether marketing spend", "Scatter chart with spend on one axis and revenue on the other", "Scatter chart with one point per store"),
 ("An analyst wants to see whether marketing spend", "Stacked column chart", "Stacked column chart of spend and revenue by store"),
 ("An analyst wants to see whether marketing spend", "Donut chart", "Donut chart of revenue by store"),
 ("Keyboard users report that tabbing", "The tab order in the Selection pane, removing decorative items from it", "The tab order in the Selection pane"),
 ("Keyboard users report that tabbing", "The visual interactions", "The visual interactions in Edit interactions mode"),
 ("Keyboard users report that tabbing", "The page size", "The page size and canvas alignment"),
 ("A DirectQuery report in a Pro workspace", "Move the workspace to Premium or Fabric capacity, where the capacity admin can allow shorter intervals", "Move the workspace to Premium or Fabric capacity"),
 ("A DirectQuery report in a Pro workspace", "Increase the scheduled refresh count to 48", "Increase the scheduled refresh count to 48 per day"),
 ("A line chart shows monthly demand estimates", "Error bars using the lower and upper bound fields", "Error bars using the bound fields"),
 ("A line chart shows monthly demand estimates", "A forecast", "A forecast with a confidence interval"),
 ("A new analyst wants a quick plain-language overview", "Copilot, asking it to summarise the semantic model", "Copilot, asked to summarise the model"),
 ("A new analyst wants a quick plain-language overview", "Query dependencies view", "Query dependencies view in Power Query"),
 ("Five hundred employees with free licences", "Put the workspace on a Fabric F64 (or Premium P1) or larger capacity and distribute through an app", "An F64 (or P1) or larger capacity, shared through an app"),
 ("Five hundred employees with free licences", "Give them the Viewer role in a Pro workspace", "Give them the Viewer role in a Pro workspace, through an app"),
 ("You publish Sales.pbix to a workspace", "Both the report and the semantic model are replaced by the versions in the file", "Both the report and the semantic model are replaced"),
 ("You publish Sales.pbix to a workspace", "A second copy named Sales (1) is created", "A second report and model named Sales (1) are created"),
 ("You want only the Data Governance team", "A Fabric administrator enables certification and specifies the Data Governance security group", "A Fabric admin enables certification for that team's group"),
 ("Each manager must see their own sales", "PATH to build a hierarchy column, and PATHCONTAINS with the signed-in user's EmployeeID found via USERPRINCIPALNAME()", "PATH and PATHCONTAINS with the signed-in user's EmployeeID"),
 ("Each manager must see their own sales", "Employee[Email] = USERPRINCIPALNAME() only", "Employee[Email] = USERPRINCIPALNAME() on the Employee table"),
 ("Each manager must see their own sales", "One static role per manager", "One static role per manager, listing each team member"),
 ("A Highly Confidential label is applied", "New reports created from the model automatically get the Highly Confidential label", "New reports inherit the Highly Confidential label"),
 ("How should you fix the Machine", "Merge the Plant and Region attributes into the Machine table in Power Query, creating one Machine dimension", "Merge Plant and Region into the Machine table in Power Query"),
 ("How should you fix the Machine", "Set every relationship in the chain to Both", "Set every relationship in the chain to Both for faster filtering"),
 ("Which design meets the plant-manager", "A PlantSecurity table with one row per manager email and plant, and a role filter on Plant: [PlantID] IN CALCULATETABLE ( VALUES ( PlantSecurity[PlantID] ), PlantSecurity[Email] = USERPRINCIPALNAME () )", "A manager–plant mapping table, filtered by USERPRINCIPALNAME() in one role"),
 ("Which design meets the plant-manager", "A filter Plant[ManagerEmail] = USERPRINCIPALNAME() on the Plant table", "A filter Plant[ManagerEmail] = USERPRINCIPALNAME() on the Plant table, in one role"),
 ("Which design meets the plant-manager", "handles managers with several plants in one dynamic role.", "handles managers with several plants in one dynamic role, with a filter on Plant such as [PlantID] IN CALCULATETABLE ( VALUES ( PlantSecurity[PlantID] ), PlantSecurity[Email] = USERPRINCIPALNAME () )."),
]
