TARGET = "sets/set05.py"
FIXES = [
 ("A government web page publishes", "Web, then select the table in the Navigator", "Web, then pick the table in the Navigator"),
 ("A government web page publishes", "Text/CSV", "Text/CSV, pointing at the page's URL"),
 ("A government web page publishes", "Blank query typed by hand", "Blank query with the figures typed in by hand"),
 ("While developing, you want Power BI Desktop to load only", "Create a numeric RowLimit parameter used in a Keep top rows step, and set a very high value in the service's parameter settings", "A RowLimit parameter in a Keep top rows step, set high in the service"),
 ("While developing, you want Power BI Desktop to load only", "Delete rows in the source during development", "Delete rows in the source during development, then restore them before publishing"),
 ("While developing, you want Power BI Desktop to load only", "Turn off Enable load in Desktop", "Turn off Enable load in Desktop and turn it back on in the service"),
 ("A Comments column contains empty text", "Use Replace values to replace an empty value with null", "Use Replace values, replacing empty text with null"),
 ("A query previews without errors in Power Query", "A value further down the data, outside the preview rows, can't be converted to the column's type", "A value outside the preview rows can't be converted"),
 ("A query previews without errors in Power Query", "The gateway is offline", "The gateway is offline, so the source can't be read during refresh"),
 ("A query previews without errors in Power Query", "The model has too many relationships", "The model has too many relationships for the refresh to complete"),
 ("An XML file contains Orders elements", "Expand the nested OrderLine table column into rows and columns", "Expand the nested OrderLine table column"),
 ("An XML file contains Orders elements", "Pivot the OrderLine column", "Pivot the OrderLine column on the order number"),
 ("In model view, a relationship between Sales and Date is drawn", "The relationship is inactive and is only used when a measure calls USERELATIONSHIP", "It is inactive and only used when a measure calls USERELATIONSHIP"),
 ("In model view, a relationship between Sales and Date is drawn", "It is a limited relationship to a DirectQuery source", "It is a limited relationship, because one side is a DirectQuery source"),
 ("Performance Analyzer shows a map visual", "Reduce the number of data points the visual renders, for example by aggregating to a coarser location level or filtering", "Render fewer points by aggregating or filtering"),
 ("Performance Analyzer shows a map visual", "Rewrite the measure", "Rewrite the measure with variables to cut query time"),
 ("Performance Analyzer shows a map visual", "Add an index column", "Add an index column to the location table to speed lookups"),
 ("Performance Analyzer identifies a slow visual", "Use Copy query in Performance Analyzer, then paste and run it in DAX query view", "Copy query, then run it in DAX query view"),
 ("Performance Analyzer identifies a slow visual", "Export the visual's data to CSV", "Export the visual's data to CSV and inspect it in Excel"),
 ("Performance Analyzer identifies a slow visual", "Use Analyze in Excel", "Use Analyze in Excel and inspect the PivotTable's query"),
 ("For one report only, you want to change the eight data colours", "View → Themes → Customize current theme, and change the data colours", "Customize current theme and change the data colours"),
 ("For one report only, you want to change the eight data colours", "Edit the corporate JSON theme file", "Edit the corporate JSON theme file, then re-import it here"),
 ("A chart title must change to reflect the selected region", "In the visual's Title, select the fx (conditional formatting) button and choose Field value with the measure", "Title → fx → Field value, choosing the measure"),
 ("A chart title must change to reflect the selected region", "Type the measure name into the title text", "Type the measure name in square brackets into the title text"),
 ("A chart title must change to reflect the selected region", "Use a bookmark per region", "Create a bookmark per region, each with its own typed title"),
 ("A Region slicer must allow only one region", "In the slicer's selection settings, turn on Single select", "Turn on Single select in the slicer settings"),
 ("A Region slicer must allow only one region", "Set the slicer to Dropdown", "Set the slicer style to Dropdown in the format settings"),
 ("A table shows profit variance", "Background colour conditional formatting using a gradient with a middle colour at 0", "Gradient background colour with a middle colour at 0"),
 ("A table shows profit variance", "Icons with three rules", "Icon conditional formatting with three rules (below, at and above 0)"),
 ("A table shows profit variance", "Data bars", "Data bars with red negative and green positive bars"),
 ("You built a report-page tooltip called Trend Tooltip", "On the Sales by Month chart, set Tooltips → Type to Report page and Page to Trend Tooltip", "On the chart, set the tooltip to the Trend Tooltip page"),
 ("You built a report-page tooltip called Trend Tooltip", "Turn on Allow use as tooltip on every page", "Turn on Allow use as tooltip on every page of the report"),
 ("You built a report-page tooltip called Trend Tooltip", "Set the tooltip page size to Letter", "Set the Trend Tooltip page's canvas size to Letter"),
 ("During a presentation, you want one visual to stand out", "Spotlight on the visual, captured in a bookmark", "Spotlight, captured in a bookmark"),
 ("Users' slicer and filter changes are kept", "Turn off the report setting that lets users save filters (persistent filters)", "Turn off persistent filters in the report settings"),
 ("Users' slicer and filter changes are kept", "Remove the users' Build permission", "Remove the users' Build permission on the semantic model"),
 ("On a kiosk-style report", "Turn off the visual header in each visual's format settings (or the report's visual header setting)", "Turn off the visual header in the format settings"),
 ("On a kiosk-style report", "Disable Edit interactions", "Set Edit interactions to None for every visual"),
 ("On a kiosk-style report", "Lock the Filters pane", "Lock and hide the Filters pane in the report settings"),
 ("A user typed a question in the Q&A visual", "Use Turn this Q&A result into a standard visual", "Turn this Q&A result into a standard visual"),
 ("A user typed a question in the Q&A visual", "Pin the Q&A visual to a dashboard", "Pin the Q&A visual to a dashboard as a new tile"),
 ("A new workspace must run on the organisation's Fabric capacity", "Workspace settings → License info (License mode), choosing Fabric capacity and the capacity", "Workspace settings → License info, choosing Fabric capacity"),
 ("A new workspace must run on the organisation's Fabric capacity", "Report settings in Power BI Desktop", "Report settings in Power BI Desktop, before publishing"),
 ("A new workspace must run on the organisation's Fabric capacity", "The gateway connection settings", "The data gateway's connection settings for the workspace"),
 ("A new workspace must run on the organisation's Fabric capacity", "The app's audience settings", "The app's audience settings, choosing a capacity per audience"),
 ("A dashboard tile must keep the interactivity", "The entire report page, as a live page tile", "The whole report page, as a live page tile"),
 ("A dashboard tile must keep the interactivity", "A screenshot of the page", "A screenshot of the page uploaded as an image tile"),
 ("A workspace admin wants to know which reports", "The usage metrics report for the reports in the workspace", "Usage metrics for the reports in the workspace"),
 ("A workspace admin wants to know which reports", "The deployment pipeline compare view", "The deployment pipeline's compare view between stages"),
 ("A semantic model's report users currently have Build permission", "In the semantic model's Manage permissions, remove Build from everyone except the analytics team, keeping Read", "Remove Build from all but the analytics team, keeping Read"),
 ("A semantic model's report users currently have Build permission", "Remove everyone from the workspace", "Remove everyone except the analytics team from the workspace"),
 ("A semantic model's report users currently have Build permission", "Apply a sensitivity label", "Apply a sensitivity label that restricts report creation"),
 ("Your organisation wants new Power BI reports and models to receive the General", "A default label for Power BI in the Microsoft Purview label policy", "A default label in the Purview label policy"),
 ("Your organisation wants new Power BI reports and models to receive the General", "A certification setting", "A certification setting in the tenant admin portal"),
 ("How should you support the board walk-through?", "Create a bookmark for each view and present them in order with a bookmark navigator (or the Bookmarks pane in View mode)", "A bookmark per view, stepped through in order"),
 ("How should you support the board walk-through?", "Create six separate reports", "Create six separate reports and link them with buttons"),
 ("How should you support the board walk-through?", "Use automatic page refresh", "Use automatic page refresh to cycle through the views"),
 ("You have a dynamic Clinic role that filters", "Create a second role, AllClinics, with no filter (or TRUE()), and add the head-office group to it", "Add the group to a second role, AllClinics, with no filter"),
 ("You have a dynamic Clinic role that filters", "Add the head-office team to the Clinic role", "Add the head-office team to the existing Clinic role as members"),
]
